//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedback.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostComment()
        {
            this.CommentsStatus = new HashSet<CommentsStatu>();
        }
    
        public int CommentId { get; set; }
        public int PostId { get; set; }
        public string Comments { get; set; }
        public int CommentsBy { get; set; }
        public System.DateTime CommentsDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentsStatu> CommentsStatus { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
